/*
 *
 * ShopPage constants
 *
 */

export const DEFAULT_ACTION = 'app/ShopPage/DEFAULT_ACTION';

export const GET_CATEGORIES = 'app/ShopPage/GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'app/ShopPage/GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'app/ShopPage/GET_CATEGORIES_FAILURE';

export const CATEGORIES_STATE_DEFAULT = 'app/ShopPage/CATEGORIES_STATE_DEFAULT';
export const CATEGORIES_STATE_FETCHING = 'app/ShopPage/CATEGORIES_STATE_FETCHING';
export const CATEGORIES_STATE_FETCHED = 'app/ShopPage/CATEGORIES_STATE_FETCHED';
export const CATEGORIES_STATE_ERROR = 'app/ShopPage/CATEGORIES_STATE_ERROR';
